# Generated by Django 3.1.3 on 2020-12-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=100)),
                ('image', models.ImageField(default=' ', upload_to='slider/')),
                ('description', models.TextField(default=' ', max_length=700)),
            ],
        ),
    ]
