# Generated by Django 3.1.3 on 2020-12-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=100)),
                ('Update', models.CharField(default=' ', max_length=80)),
                ('description', models.TextField(default=' ', max_length=12000)),
            ],
        ),
    ]
